# Generated by Django 6.0.6 on 2026-06-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Aluno')),
                ('status', models.CharField(max_length=50, verbose_name='Situação')),
                ('total_absences', models.IntegerField(default=0, verbose_name='Total Faltas Bimestre')),
                ('frequency_pct', models.CharField(blank=True, max_length=10, null=True, verbose_name='Frequência Bimestre')),
                ('total_absences_annual', models.IntegerField(default=0, verbose_name='Total Faltas Anual')),
                ('frequency_pct_annual', models.CharField(blank=True, max_length=10, null=True, verbose_name='Frequência Anual')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Disciplina')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='ComponentGradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(blank=True, max_length=10, null=True, verbose_name='Atividades')),
                ('assignments', models.CharField(blank=True, max_length=10, null=True, verbose_name='Trabalhos')),
                ('tests', models.CharField(blank=True, max_length=10, null=True, verbose_name='Provas')),
                ('prova_paulista', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prova Paulista')),
                ('final_average', models.CharField(blank=True, max_length=10, null=True, verbose_name='Média Final')),
                ('observation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação/Situação')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_grades', to='dashboard.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_grades', to='dashboard.subject')),
            ],
            options={
                'verbose_name': 'Detalhe de Nota Técnica',
                'verbose_name_plural': 'Detalhes de Notas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='SubjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Média')),
                ('absences', models.IntegerField(default=0, verbose_name='Faltas')),
                ('compensated_lessons', models.IntegerField(default=0, verbose_name='Aulas Compensadas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.subject')),
            ],
            options={
                'verbose_name': 'Métrica de Disciplina',
                'verbose_name_plural': 'Métricas das Disciplinas',
            },
        ),
    ]
